In [52]:
import numpy as np

# Soal 1

### Buat array berisi angka 0-9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arrA = np.arange(0,10)
arrA

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Buat matrix berukuran 2x5 berisi angka 0-9

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
arrA.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
arrA.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [72]:
arrB = np.arange(0,20)
arrB

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [74]:
arrB.reshape(2,2,-1)
# -1 menyesuaikan dgn sisa yg belum dibagi, 
# jadi 20 dibagi 2, lalu dibagi 2, kemudian sisanya 1 elemen berisi 5

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [77]:
arrB.reshape(2,-1, 2)
# jadi 20 dibagi 2 dibagi, lalu sisanya adalah 10, kemudian dibagi masing2 elemen berisi 2

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Soal 2

In [79]:
arr = np.arange(4,13).reshape(3,3)
arr

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### dari matrix arr, lakukan indexing untuk membuat array berikut

array([[ 5,  6,  4,  4,  5,  6,  5],
       [ 8,  9,  7,  7,  8,  9,  8],
       [11, 12, 10, 10, 11, 12, 11]])

In [80]:
# indexing column 
a = arr[:,0:1]
b = arr[:,1:2]
c = arr[:,2:3]

# merangkai masing2 column dgn concatenate(()) , axis=1 untuk horizontal 
newArr = np.concatenate((b,c,a,a,b,c,b), axis=1)
newArr


array([[ 5,  6,  4,  4,  5,  6,  5],
       [ 8,  9,  7,  7,  8,  9,  8],
       [11, 12, 10, 10, 11, 12, 11]])

In [81]:
arr[:,[1,2,0,0,1,2,1]]
# indexing menggunakan [row,column] bisa menjadi berlipat jika kita masukkan index yg sama di dalam list row atau column yg diinginkan

array([[ 5,  6,  4,  4,  5,  6,  5],
       [ 8,  9,  7,  7,  8,  9,  8],
       [11, 12, 10, 10, 11, 12, 11]])

## Soal 3

In [82]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### dari matrix arr, lakukan indexing untuk membuat array berikut

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [83]:
arr[:, ::-1]
# array[column, row]
# : adalah semua baris
# ::-1 adalah untuk membalik urutan

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [90]:
np.flip(arr, axis=1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

## Soal 4

In [84]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays

array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

### dari 3 array di atas, buat satu array seperti berikut

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
# merangkai beberapa array dengan concatenate([]) 
arrUnited = np.concatenate([arr1, arr2 , arr3])
arrUnited


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
# atau concatenate(())
arrUnited = np.concatenate((arr1, arr2 , arr3))
arrUnited

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])