# NUMPY

In [218]:
# import library numpy
import numpy as np

In [219]:
# array 1 dimensi
mylist = [1,2,3]
np.array(mylist)

array([1, 2, 3])

In [220]:
# cek data type
type(np.array(mylist))

numpy.ndarray

In [221]:
# array 2 dimensi
mymatrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [222]:
# array 3 dimensi
my3dlist = [ [ [1,2],[3,4] ],
             [ [5,6],[7,8] ] ]
np.array(my3dlist)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [223]:
x = np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [224]:
y = np.arange(0,10,2) # start, stop, step
y

array([0, 2, 4, 6, 8])

In [225]:
type(x)

numpy.ndarray

In [226]:
type(y)

numpy.ndarray

In [227]:
# ## **Mini Activity**

# - **Group 1** : 
# - np.linspace, 
# - np.zeros, 
# - arr.shape,
# - arr.reshape

# - **Group 2**: 
# - np.ones,  
# - np.random.rand, 
# - np.random.randn, 
# - np.random.randint


# - **Group 3**: 
# - arr.max, 
# - arr.argmax, 
# - arr.min, 
# - arr.argmin, 
# - arr.dtype

# Cara pemakaian  
# Fungsi method  
# Aplikasinya apa  


# LINSPACE, ZEROS, ONES, EYE

In [228]:
# membuat array dgn jarak antar elemennya sama
# deret bilangan (start, stop, step) 
np.linspace(1,100,6) 

array([  1. ,  20.8,  40.6,  60.4,  80.2, 100. ])

In [229]:
np.eye(5,5) 
# membentuk angka 1 diagonal diantara angka-angka 0

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [230]:
np.zeros(5) 
# membuat array berisi angka 0, 1 dimensi

array([0., 0., 0., 0., 0.])

In [231]:
np.zeros((5,2)) 
# membuat array berisi angka 0, 
# 2 dimensi, ditulis dgn tuple

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [232]:
np.zeros((5,2,2)) # 3 dimensi, ditulis dgn tuple

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [233]:
np.zeros((5,2), dtype=int) 
# tambah parameter dtype untuk mengubah data typenya

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [236]:
np.ones((5,2), dtype=int, order='F')
# membuat data dummy dgn array berapa dimensi
# bisa menentukan data typenya int / float

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

# SHAPE & RESHAPE

In [249]:
arr = np.array([[1,2,8,4],[5,6,7,3]])
print(arr.shape)
# bentuk dari array, hitung element dari kurung paling dalam

(2, 4)


In [252]:
arrB = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arrB.reshape(2,3,2))
# mengubah bentuk/shape
# shape baru sesuai dgn jumlah elemen dalam array


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(12,)


# RANDOM

In [237]:
np.random.rand(3,4)
# memasukkan angka random antara -1 sampai 1 
# bentuknya dimasukkan di parameternya 

array([[0.94243034, 0.12000618, 0.14825901, 0.57610911],
       [0.87140013, 0.84216943, 0.37823434, 0.7932978 ],
       [0.0590984 , 0.61162097, 0.851772  , 0.67685612]])

In [238]:
np.random.randn(3,4)
# memasukkan angka random antara -1 sampai 1 (mayoritas)
# bisa jadi ada angka <-1 atau >1
# bentuknya dimasukkan di parameternya 

array([[ 1.34950759,  0.65786008, -1.0541541 , -2.73676231],
       [-0.24800248, -2.06365311,  1.08072392, -0.55437985],
       [ 0.26475159,  0.39927754,  1.01425751,  0.50898157]])

In [247]:
np.random.randint(0,100, size=5)
# memasukkan angka random antara parameter yg dimasukkan sebanyak size

array([67, 81, 66, 49, 79])

In [246]:
np.random.randint(1,[3,30,100])
# memasukkan angka random antara parameter yg dimasukkan
# 1-3, 1-30, 1-100

array([ 2, 29, 64])

# MAX ARGMAX MIN ARGMIN DTYPE

In [241]:
arr = np.array([[1,2,8,4],[5,6,7,3]])

print(arr.max())
# nilai max pada array

8


In [242]:
print(arr.argmax())
# index dari angka tertinggi

print(arr.argmax(axis=0)) # index dari angka tertinggi antara 2 elemen
print(arr.argmax(axis=1)) # index dari angka tertinggi dalam 1 baris


2
[1 1 0 0]
[2 2]


In [243]:
print(arr.min())
# nilai minimum pada array

1


In [244]:
print(arr.argmin())
print(arr.argmin(axis=0))
print(arr.argmin(axis=1))
# index dari angka terendah

0
[0 0 1 1]
[0 3]


In [245]:
print(arr.dtype)


int32


In [258]:
z=(np.int64(arr))
print(z.dtype)

z=(np.float64(arr))
print(z.dtype)

int64
float64


# INDEXING

In [261]:
a = np.arange(11,21)
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [262]:
a[8]

19

In [263]:
a[0:8:2]

array([11, 13, 15, 17])

In [264]:
a = a.reshape(2,5)
a

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [265]:
a[0][1]

12

#  BROADCASTING 

In [267]:
a = np.arange(11,21)
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [270]:
a[0:4] = 0
a

array([ 0,  0,  0,  0, 15, 16, 17, 18, 19, 20])

# SLICING 

In [281]:
sliceA = a[5:9]
sliceA

array([ 1, 17, 18, 19])

In [282]:
sliceA[0:] = 1
a 
# nilai a jadi berubah karena sliceA hanya berupa view dari array a

array([ 0,  0,  0,  0, 15,  1,  1,  1,  1, 20])

# COPY

In [284]:
c = a[5:10].copy()
c

array([ 1,  1,  1,  1, 20])

# INDEXING 2D ARRAY

In [285]:
arr2D = np.array(([5,10,15],[20,25,10],[15,35,25]))
arr2D

array([[ 5, 10, 15],
       [20, 25, 10],
       [15, 35, 25]])

In [286]:
yo = arr2D[0,1], arr2D[1,1], arr2D[2,1]
np.array(yo)

array([10, 25, 35])

In [287]:
arr2D[1]

array([20, 25, 10])

In [288]:
arr2D[0][2]

15

In [289]:
arr2D[0,2]

15

# 2D ARRAY SLICING

In [291]:
arr2D

array([[ 5, 10, 15],
       [20, 25, 10],
       [15, 35, 25]])

In [293]:
arr2D[:3, :2]
# dalam [[]] slicing :3
# dalam [] slicing :2

array([[ 5, 10],
       [20, 25],
       [15, 35]])

In [294]:
arr2D[2]

array([15, 35, 25])

In [298]:
arr2D[2, :]

array([15, 35, 25])

# LENGTH OF ARRAY

In [300]:
arr2D = np.zeros((10,5))
arr2D

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [301]:
len(arr2D) 
# panjang/ banyaknya [],[],[]

10

In [302]:
arr_length = arr2D.shape[0]
arr_length

10

# SELECTION

In [303]:
gaji = np.arange(5, 25)
gaji

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [304]:
# selection gaji > 10jt
gaji>10

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [305]:
bool_gaji = gaji>10
gaji[bool_gaji]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [306]:
gaji[gaji>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

# ARITMETHIC

In [308]:
x = np.arange(5,15)
y = np.arange(15,25)
print(x)
print(y)

[ 5  6  7  8  9 10 11 12 13 14]
[15 16 17 18 19 20 21 22 23 24]


In [309]:
x

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [310]:
y

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [311]:
x + y

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [312]:
x - y

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [313]:
y/x

array([3.        , 2.66666667, 2.42857143, 2.25      , 2.11111111,
       2.        , 1.90909091, 1.83333333, 1.76923077, 1.71428571])

In [314]:
x*y

array([ 75,  96, 119, 144, 171, 200, 231, 264, 299, 336])

In [316]:
pangkatDua = x ** 2
pangkatDua

array([ 25,  36,  49,  64,  81, 100, 121, 144, 169, 196], dtype=int32)

In [317]:
np.sqrt(pangkatDua)

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.])

In [319]:
np.exp(x)

array([1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06])

In [320]:
np.sin(x)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736])

In [321]:
np.log(x)

array([1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733])

In [322]:
z = x.reshape(2,5)
z

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [323]:
z*2

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [324]:
a = np.arange(1,4)
a

array([1, 2, 3])

In [325]:
z*a # error karena shapenya ga sama

ValueError: operands could not be broadcast together with shapes (2,5) (3,) 

In [327]:
b = np.arange(2,7)
b

array([2, 3, 4, 5, 6])

In [328]:
z*b
# setiap row dikali dgn yg berpasangan indexnya

array([[10, 18, 28, 40, 54],
       [20, 33, 48, 65, 84]])

In [329]:
c = np.array([[1],[2]])
c

array([[1],
       [2]])

In [330]:
z*c

array([[ 5,  6,  7,  8,  9],
       [20, 22, 24, 26, 28]])

In [333]:
# untuk melakukan operasi matematika antar array, ukuran array di dimensi yang sama/ salah satunya bernilai 1

In [334]:
np.dot(x,y) # perkalian matrix

1935

In [335]:
x@y # perkalian matrix

1935