# Import NumPy as np

In [43]:
import numpy as np

# Create an array of 10 zeros 

In [44]:
arrZero = np.zeros(10)
arrZero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Create an array of 10 ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
arrOne = np.ones(10)
arrOne

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Create an array of 10 fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [46]:
arrFive = np.full(shape=10, fill_value=5, dtype=float)
arrFive

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [47]:
arrFive = np.ones(10)*5
arrFive

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [48]:
arrFive = np.zeros(10)+5
arrFive

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [49]:
arrFive = np.linspace(5,5,10)
arrFive

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# Create an array of the integers from 10 to 50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [50]:
arr_10_50 = np.arange(10,51)
arr_10_50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

# Create an array of all the even integers from 10 to 50

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [51]:
arr_10_50_2 = np.arange(10,51,2)
arr_10_50_2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

# Create a 3x3 matrix with values ranging from 0 to 8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
matrixA = [[0,1,2],[3,4,5],[6,7,8]]
np.array(matrixA)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
matrixA = np.arange(0,9)
matrixA.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
matrixIdt = np.eye(3,3)
matrixIdt

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Use NumPy to generate a random number between 0 and 1

array([0.9074019])

In [55]:
randomA = np.random.random(1)
randomA

array([0.24755566])

In [56]:
randomA = np.random.rand(1)
randomA

array([0.54908975])

In [57]:
randomA = np.random.uniform(0,1)
randomA

0.31095585750469534

In [58]:
randomA = np.random.random(1)
randomA

array([0.89716713])

In [59]:
randomA = np.random.uniform(0,1)
randomA

0.2030864162366376

# Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [60]:
randomNormal = np.random.randn(25)
randomNormal

array([ 0.92401674, -1.05596252, -0.9675626 ,  0.06002305,  1.32702201,
       -0.01719689, -2.60418087,  1.64395931, -2.087855  ,  0.25249707,
       -1.63993109,  1.00327856, -1.11267724,  0.93721265,  0.80286961,
       -0.30608767,  0.64453584,  0.43705598, -1.64790676, -1.32352159,
        0.30261618, -0.95171826,  0.40350703,  1.14433025, -0.35026225])

In [61]:
randomNormal = np.random.standard_normal(25)
randomNormal

array([-2.29077992,  1.26144128, -0.7458618 , -1.12813122,  0.59543201,
        1.04265622, -0.39842956,  0.57553073, -0.99635777,  0.61892687,
        2.07899547,  1.13343612,  1.04163562, -0.34650332,  1.6009369 ,
        1.57404175, -0.93984686,  0.35345131,  1.01224289,  0.07157861,
       -0.32243767,  0.09566302, -0.26576756, -0.79627283,  1.94320196])

array([[ 0.31555954, -0.37995862,  0.63999968,  0.70593703,  0.38291606,
         0.25071859, -0.18832699,  0.37893178,  0.16967005, -0.23021395,
        -1.03630702,  0.34761185,  1.19947461,  0.19425825,  0.29500492,
        -0.50881071,  0.37883307,  0.4131713 ,  0.01795787,  2.37645248,
         0.01869522, -0.67837459,  0.3668847 ,  0.42082921, -1.06496711]])

# Create the following matrix:

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [62]:
randomB = np.linspace(0.01,1,100)
randomB

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [63]:
randomB = np.linspace(0.01,1,100)
randomB.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [64]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

# Create an array of 20 linearly spaced points between 0 and 1:

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [65]:
randomC = np.linspace(0,1, num=20)
randomC

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [66]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [67]:
mat[2:5, 1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

20

In [68]:
mat[3][4]

20

In [69]:
mat[3,4]

20

array([[ 2],
       [ 7],
       [12]])

In [70]:
mat[0:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

array([21, 22, 23, 24, 25])

In [71]:
mat[-1, :]

array([21, 22, 23, 24, 25])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [72]:
mat[3:5, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Now do the following

In [73]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Get the sum of all the values in mat

325

In [74]:
np.sum(mat)

325

In [75]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [76]:
np.std(mat)

7.211102550927978

7.211102550927978

#### Get the sum of all the columns in mat

array([55, 60, 65, 70, 75])

In [77]:
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])

In [78]:
np.sum(mat, axis=1)

array([ 15,  40,  65,  90, 115])